|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |


- In the context of this problem, what is a false positive?
    Actual dog/predicted cat
- In the context of this porblem, what is a false negative?
    Actual cat/predicted dog
- How would you describe this model?  tp = 46 , tn = 34, fp = 13, fn = 7
    

In [26]:
tp = 46
tn = 34
fp = 13
fn = 7

In [27]:
print('True Positives =', tp)
print('True Negatives =', tn)
print('False Positives =', fp)
print('False Negatives =', fn)

True Positives = 46
True Negatives = 34
False Positives = 13
False Negatives = 7


In [43]:
import pandas as pd
import numpy as np
import acquire
import prepare
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [15]:
def show_confusion():
    from IPython import display
    return display.Image("https://raw.githubusercontent.com/David-Howell/classification-exercises/main/annotated_confusion_matrix.png")

In [2]:
c3 = pd.read_csv('c3.csv')
c3

actual     model1     model2     model3
0    No Defect  No Defect     Defect  No Defect
1    No Defect  No Defect     Defect     Defect
2    No Defect  No Defect     Defect  No Defect
3    No Defect     Defect     Defect     Defect
4    No Defect  No Defect     Defect  No Defect
..         ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect
196     Defect     Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect
199  No Defect  No Defect  No Defect     Defect

[200 rows x 4 columns]

In [4]:
c3['actual'].value_counts()

No Defect    184
Defect        16
Name: actual, dtype: int64

In [6]:
confusion_matrix(c3.actual, c3.model1, labels = ('No Defect', 'Defect'))

array([[182,   2],
       [  8,   8]])

In [7]:
confusion_matrix(c3.actual, c3.model2, labels = ('No Defect', 'Defect'))

array([[103,  81],
       [  7,   9]])

In [8]:
confusion_matrix(c3.actual, c3.model3, labels = ('No Defect', 'Defect'))

array([[98, 86],
       [ 3, 13]])

- An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [55]:
# Recall would be the best evaluation metric

# spec1 = 182/(182+8)
# spec2 = 103/(103+7)
# spec3 = 98/(98+3)

# spec1, spec2, spec3

print(recall_score(c3.actual, c3.model1, pos_label= 'Defect'))
print(recall_score(c3.actual, c3.model2, pos_label= 'Defect'))
print(recall_score(c3.actual, c3.model3, pos_label= 'Defect'))

0.5
0.5625
0.8125


In [11]:
# model 3 has the highest recall rate

- Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [56]:
# precision would be the best evaluation metric for this issue

print(precision_score(c3.actual, c3.model1, pos_label= 'Defect'))
print(precision_score(c3.actual, c3.model2, pos_label= 'Defect'))
print(precision_score(c3.actual, c3.model3, pos_label= 'Defect'))

0.8
0.1
0.13131313131313133


In [17]:
# model 1 has the highest precision rate

You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

In [19]:
paws = pd.read_csv('gives_you_paws.csv')
paws

actual model1 model2 model3 model4
0       cat    cat    dog    cat    dog
1       dog    dog    cat    cat    dog
2       dog    cat    cat    cat    dog
3       dog    dog    dog    cat    dog
4       cat    cat    cat    dog    dog
...     ...    ...    ...    ...    ...
4995    dog    dog    dog    dog    dog
4996    dog    dog    cat    cat    dog
4997    dog    cat    cat    dog    dog
4998    cat    cat    cat    cat    dog
4999    dog    dog    dog    dog    dog

[5000 rows x 5 columns]

a. In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?

In [20]:
paws.actual.value_counts()

dog    3254
cat    1746
Name: actual, dtype: int64

In [21]:
paws['baseline_prediction']= 'dog'

In [22]:
paws

actual model1 model2 model3 model4 baseline_prediction
0       cat    cat    dog    cat    dog                 dog
1       dog    dog    cat    cat    dog                 dog
2       dog    cat    cat    cat    dog                 dog
3       dog    dog    dog    cat    dog                 dog
4       cat    cat    cat    dog    dog                 dog
...     ...    ...    ...    ...    ...                 ...
4995    dog    dog    dog    dog    dog                 dog
4996    dog    dog    cat    cat    dog                 dog
4997    dog    cat    cat    dog    dog                 dog
4998    cat    cat    cat    cat    dog                 dog
4999    dog    dog    dog    dog    dog                 dog

[5000 rows x 6 columns]

In [23]:
base_accuracy = (paws.baseline_prediction == paws.actual).mean()
m1_accuracy = (paws.model1 == paws.actual).mean()
m2_accuracy = (paws.model2 == paws.actual).mean()
m3_accuracy = (paws.model3 == paws.actual).mean()
m4_accuracy = (paws.model4 == paws.actual).mean()

print(f' model1 accuracy: {m1_accuracy:.2%}')
print(f' model2 accuracy: {m2_accuracy:.2%}')
print(f' model3 accuracy: {m3_accuracy:.2%}')
print(f' model4 accuracy: {m4_accuracy:.2%}')
print(f'baseline accuracy: {base_accuracy:.2%}')

 model1 accuracy: 80.74%
 model2 accuracy: 63.04%
 model3 accuracy: 50.96%
 model4 accuracy: 74.26%
baseline accuracy: 65.08%


In [24]:
# model 1, 3, and 4 have better accuracy than the baseline.

b. Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I?

In [33]:
model_pre = []

for model in paws.columns[1:]:
    subset = paws[paws[model] == 'dog']
    precision = (subset.actual == subset[model]).mean()
    model_pre.append([model, precision])
model_pre

[['model1', 0.8900238338440586],
 ['model2', 0.8931767337807607],
 ['model3', 0.6598883572567783],
 ['model4', 0.7312485304490948],
 ['baseline_prediction', 0.6508]]

In [34]:
# model 1 would be the best model for team dealing with dog pictures

c. Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I?

In [40]:
model_pre = []

for model in paws.columns[1:]:
    subset = paws[paws[model] == 'cat']
    precision = (subset.actual == subset[model]).mean()
    model_pre.append([model,precision])
model_pre

[['model1', 0.6897721764420747],
 ['model2', 0.4841220423412204],
 ['model3', 0.358346709470305],
 ['model4', 0.8072289156626506],
 ['baseline_prediction', nan]]

In [41]:
# model 4 would be the best model for team dealing with cat pictures

In [37]:
from sklearn.metrics import classification_report

In [ ]:
sklearn.metrics.accuracy_score

In [ ]:
sklearn.metrics.precision_score

In [ ]:
sklearn.metrics.recall_score

In [39]:
pd.DataFrame(classification_report(paws.actual, paws.model1, labels = ['cat', 'dog'], output_dict=True))

cat          dog  accuracy    macro avg  weighted avg
precision     0.689772     0.890024    0.8074     0.789898      0.820096
recall        0.815006     0.803319    0.8074     0.809162      0.807400
f1-score      0.747178     0.844452    0.8074     0.795815      0.810484
support    1746.000000  3254.000000    0.8074  5000.000000   5000.000000